# Generated by Django 4.1.5 on 2023-01-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="passenger_num",
            field=models.IntegerField(),
        ),
    ]
