# Generated by Django 4.1.5 on 2023-02-01 00:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride", "0002_alter_owner_passenger_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "ride_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for the ride",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("destination_addr", models.CharField(max_length=20)),
                ("arrival_date", models.DateTimeField()),
                (
                    "passenger_num",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("e", "economy"), ("l", "luxury")],
                        default="e",
                        help_text="Vehicle type",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("o", "open"), ("c", "confirmed"), ("f", "complete")],
                        default="o",
                        help_text="Ride status",
                        max_length=1,
                    ),
                ),
                (
                    "special_request",
                    models.TextField(
                        blank=True, help_text="E.g. Assistance", max_length=200
                    ),
                ),
                ("if_share", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Sharer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_num",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("earliest_date", models.DateTimeField()),
                ("latest_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                choices=[("e", "economy"), ("l", "luxury")],
                default="e",
                help_text="Vehicle type",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="max_num_passengers",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="special_request",
            field=models.TextField(
                blank=True, help_text="E.g Assistance", max_length=200
            ),
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.AddField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ride.driver",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="sharer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ride.sharer",
            ),
        ),
    ]
