# Generated by Django 4.1.5 on 2023-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0004_alter_driver_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "open"),
                    ("confirmed", "confirmed"),
                    ("complete", "complete"),
                ],
                default="open",
                help_text="Ride status",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(
                choices=[("economy", "economy"), ("luxury", "luxury")],
                default="economy",
                help_text="Vehicle type",
                max_length=10,
            ),
        ),
    ]
