# Generated by Django 4.1.5 on 2023-02-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0005_alter_ride_status_alter_ride_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                choices=[("economy", "economy"), ("luxury", "luxury")],
                default="economy",
                help_text="Vehicle type",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="special_request",
            field=models.TextField(
                blank=True, help_text="E.g. Assistance", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "open"),
                    ("confirmed", "confirmed"),
                    ("complete", "complete"),
                ],
                default="open",
                help_text="Ride status",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(
                choices=[("economy", "economy"), ("luxury", "luxury")],
                default="economy",
                help_text="Vehicle type",
                max_length=100,
            ),
        ),
    ]
