# Generated by Django 4.1.5 on 2023-02-02 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride", "0010_alter_ride_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("economy", "economy"), ("luxury", "luxury")],
                default="economy",
                help_text="Vehicle type",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("economy", "economy"), ("luxury", "luxury")],
                default="economy",
                help_text="Vehicle type",
                max_length=100,
                null=True,
            ),
        ),
    ]
