# Generated by Django 4.1.5 on 2023-02-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0011_alter_driver_user_alter_driver_vehicle_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="sharer",
        ),
        migrations.AddField(
            model_name="ride",
            name="sharer",
            field=models.ManyToManyField(blank=True, null=True, to="ride.sharer"),
        ),
    ]
