# Generated by Django 4.1.5 on 2023-02-03 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0012_remove_ride_sharer_ride_sharer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="sharer",
        ),
        migrations.AddField(
            model_name="ride",
            name="sharer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ride.sharer",
            ),
        ),
    ]
