# Generated by Django 4.1.5 on 2023-02-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0016_remove_ride_sharer_ride_multi_sharer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="multi_sharer",
            new_name="sharer",
        ),
    ]
