# Generated by Django 4.1.5 on 2023-02-04 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0018_remove_ride_sharer_ride_sharer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="arrival_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
