# Generated by Django 4.1.5 on 2023-02-04 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0019_alter_ride_arrival_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharer",
            name="earliest_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="sharer",
            name="latest_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
