# Generated by Django 4.1.5 on 2023-02-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0020_alter_sharer_earliest_date_alter_sharer_latest_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="sharer",
        ),
        migrations.AddField(
            model_name="sharer",
            name="ride",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ride.ride",
            ),
        ),
        migrations.AlterField(
            model_name="sharer",
            name="destination_addr",
            field=models.CharField(max_length=20),
        ),
    ]
