# Generated by Django 4.1.5 on 2023-02-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0021_remove_ride_sharer_sharer_ride_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharer",
            name="ride",
        ),
        migrations.AddField(
            model_name="sharer",
            name="ride_unique_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
