# Generated by Django 4.1.5 on 2023-02-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0024_remove_sharer_destination_addr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharer",
            name="ride_joined",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ride.ride",
            ),
        ),
    ]
