# Generated by Django 4.1.5 on 2023-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0026_alter_driver_user_alter_driver_vehicle_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="special_request",
            field=models.TextField(
                blank=True, help_text="E.g. Assistance", max_length=1000, null=True
            ),
        ),
    ]
