# Generated by Django 4.1.5 on 2023-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0027_alter_ride_special_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Sedan", "Sedan"),
                    ("Coupe", "Coupe"),
                    ("Hatchback", "Hatchback"),
                    ("SUV", "SUV"),
                ],
                default="economy",
                help_text="Vehicle type",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sedan", "Sedan"),
                    ("Coupe", "Coupe"),
                    ("Hatchback", "Hatchback"),
                    ("SUV", "SUV"),
                ],
                default="Sedan",
                help_text="Vehicle type",
                max_length=100,
                null=True,
            ),
        ),
    ]
