# Generated by Django 4.1.5 on 2023-02-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0028_alter_driver_vehicle_type_alter_ride_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Sedan", "Sedan"),
                    ("Coupe", "Coupe"),
                    ("Hatchback", "Hatchback"),
                    ("SUV", "SUV"),
                ],
                default="Sedan",
                help_text="Vehicle type",
                max_length=10,
            ),
        ),
    ]
