# Generated by Django 4.1.5 on 2023-02-06 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0029_alter_driver_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="max_num_passengers",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="passenger_num",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
