# Generated by Django 4.1.5 on 2023-02-06 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0030_alter_driver_max_num_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='passenger_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
